import { index, layout, type RouteConfig, route } from '@react-router/dev/routes';

export default [
  index('routes/index.tsx'),
  route('dashboard', 'routes/dashboard/index.tsx'),
  layout('routes/(auth)/layout.tsx', [
    route('login', 'routes/(auth)/login/index.tsx'),
    route('signup', 'routes/(auth)/signup/index.tsx'),
  ]),
  route('onboarding', 'routes/onboarding/index.tsx'),
  route('invite/:token', 'routes/invite/[token]/index.tsx'),
  route('ui', 'routes/ui/index.tsx'),
  route('ui/errors', 'routes/ui/errors/index.tsx'),
  route('design.md', 'routes/design.md/index.ts'),
  route('admin', 'routes/admin/layout.tsx', [
    index('routes/admin/index.tsx'),
    route('workspaces', 'routes/admin/workspaces/index.tsx'),
    route('rates', 'routes/admin/rates/index.ts'),
  ]),
  route(':slug/onboarding/*', 'routes/[slug]/onboarding/index.tsx'),
  route(':slug', 'routes/[slug]/layout.tsx', [
    index('routes/[slug]/index.tsx'),
    route('search', 'routes/[slug]/search/index.ts'),
    route('subscribers', 'routes/[slug]/subscribers/index.tsx'),
    route('segments', 'routes/[slug]/segments/index.tsx'),
    route('segments/new', 'routes/[slug]/segments/new/index.tsx'),
    route('segments/:segmentSlug', 'routes/[slug]/segments/[segmentSlug]/index.tsx'),
    route('topics', 'routes/[slug]/topics/index.tsx'),
    route('messages', 'routes/[slug]/messages/index.tsx'),
    route('messages/:id', 'routes/[slug]/messages/[id]/index.tsx'),
    route('campaigns', 'routes/[slug]/campaigns/index.tsx'),
    route('campaigns/new', 'routes/[slug]/campaigns/new/index.tsx'),
    route('campaigns/:campaignSlug', 'routes/[slug]/campaigns/[campaignSlug]/index.tsx'),
    route('workflows', 'routes/[slug]/workflows/index.tsx'),
    route('workflows/new', 'routes/[slug]/workflows/new/index.tsx'),
    route('workflows/secrets', 'routes/[slug]/workflows/secrets/index.tsx'),
    route('workflows/:workflowSlug', 'routes/[slug]/workflows/[workflowSlug]/index.tsx'),
    route('workflows/:workflowSlug/test', 'routes/[slug]/workflows/[workflowSlug]/test/index.tsx'),
    route('runs', 'routes/[slug]/runs/index.tsx'),
    route('runs/:runId', 'routes/[slug]/runs/[runId]/index.tsx'),
    route('events', 'routes/[slug]/events/index.tsx'),
    route('events/stream', 'routes/[slug]/events/stream/index.tsx'),
    route('events/:name', 'routes/[slug]/events/[name]/index.tsx'),
    route('keys', 'routes/[slug]/keys/index.tsx'),
    route('webhooks', 'routes/[slug]/webhooks/index.tsx'),
    route('webhooks/:id', 'routes/[slug]/webhooks/[id]/index.tsx'),
    route('sources', 'routes/[slug]/sources/index.tsx'),
    route('sources/:id', 'routes/[slug]/sources/[id]/index.tsx'),
    route('subscribers/:externalId', 'routes/[slug]/subscribers/[externalId]/index.tsx'),
    route('settings', 'routes/[slug]/settings/layout.tsx', [
      index('routes/[slug]/settings/index.tsx'),
      route('channels', 'routes/[slug]/settings/channels/index.tsx'),
      route('members', 'routes/[slug]/settings/members/index.tsx'),
      route('tenants', 'routes/[slug]/settings/tenants/index.tsx'),
      route('audit-log', 'routes/[slug]/settings/audit-log/index.tsx'),
    ]),
    route('*', 'routes/[slug]/planned/index.tsx'),
  ]),
] satisfies RouteConfig;
